import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';

for (const voice of ['v7', 'v8']) test(`V8 generation with ${voice}: choices, lyrics and version survive reloads`, async ({ page }) => {
  test.setTimeout(90000);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  const base = 'http://127.0.0.1:3000/yehry3';
  const workerId = randomUUID();
  const headers = { Authorization: 'Bearer v8-local-test-worker-token-only-1234567890', 'X-Worker-ID': workerId, 'Content-Type': 'application/json' };
  const call = async (path, body) => {
    const response = await fetch(base + '/worker' + path, { method: body ? 'POST' : 'GET', headers, ...(body ? { body: JSON.stringify(body) } : {}) });
    const data = await response.json(); expect(response.status, JSON.stringify(data)).toBe(200); return data;
  };
  let leaseToken = randomUUID();
  const claim = async () => { leaseToken = randomUUID(); return (await call('/claim', { claimId: randomUUID(), leaseToken, capabilities: ['request-materials-v1','generation-v8-v1','voice-v8-v1'] })).prompt; };
  await page.goto('/distonyc/');
  await page.locator('#password').fill('wishbone'); await page.locator('#login-form button').click();
  await page.locator('#idea').fill('V8 browser test: a piano waltz about a morning train.');
  await page.locator('#idea-form button').click();
  await expect(page.locator('#voice-model')).toHaveValue('v7');
  expect(await page.locator('#voice-model option').evaluateAll(options => options.map(o => o.value))).toEqual(['v6', 'v7', 'v8']);
  await page.locator('#voice-model').selectOption('v6'); await expect(page.locator('#voice-model')).toHaveValue('v6');
  await page.locator('#voice-model').selectOption(voice);
  await page.getByRole('tab', { name: 'Advanced', exact: true }).click();
  if (voice === 'v8') {
    await expect(page.locator('#generation-enabled')).toBeChecked();
    await expect(page.locator('#generation-enabled')).toBeDisabled();
    await expect(page.locator('#generation-mode-note')).toContainText('Tony V8 uses V8 song generation');
  } else await page.locator('#generation-enabled').check();
  for (const summary of await page.locator('.generation-group summary').all()) await summary.click();
  await page.locator('#gen-genre').fill('Piano waltz'); await page.locator('#gen-instruments').fill('piano\ncello');
  await page.locator('#gen-duration').fill('120'); await page.locator('#gen-bpm').fill('98');
  await page.locator('#gen-keyscale').selectOption('D minor'); await page.locator('#gen-meter').selectOption('3/4');
  await page.locator('#gen-lyricWorkflow').selectOption('story'); await page.locator('#gen-avoidPhrases').fill('crooked grin\nshoes');
  await page.locator('#gen-lockedLines').fill('Carry me home across the rain'); await page.locator('#gen-candidates').fill('2');
  await page.locator('#gen-reviewLyrics').check(); await page.locator('#generation-remember').click();
  await expect(page.locator('#generation-preference-status')).toContainText('Remembered');
  await page.reload(); await expect(page.locator('#generation-enabled')).toBeChecked();
  await expect(page.locator('#voice-model')).toHaveValue(voice);
  await expect(page.locator('#gen-bpm')).toHaveValue('98'); await expect(page.locator('#gen-avoidPhrases')).toHaveValue('crooked grin\nshoes');
  for (const summary of await page.locator('.generation-group summary').all()) await summary.click();
  await page.screenshot({ path: 'artifacts/v8/advanced-desktop.png', fullPage: true });
  await page.locator('#details-form > .actions .primary').click();
  await expect(page.locator('.generation-brief')).toContainText('98');
  await page.locator('#confirm-form .primary').click();
  const draftId = await page.evaluate(() => sessionStorage.getItem('yehry3:draft'));
  const savedDraft = await page.evaluate(async (id) => (await (await import('/assets/api.js')).api(`/prompts/${id}`, { role: 'submitter' })).prompt, draftId);
  const adminVisitor = randomUUID();
  const adminSession = await fetch(base + '/session', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Visitor-ID': adminVisitor }, body: JSON.stringify({ role: 'admin', password: process.env.YEHRY3_TEST_ADMIN_PASSWORD || 'v8-local-preview-admin' }) });
  expect(adminSession.status).toBe(200);
  const adminToken = (await adminSession.json()).token;
  const priority = await fetch(base + `/admin/prompts/${draftId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'X-Visitor-ID': adminVisitor, Authorization: 'Bearer ' + adminToken }, body: JSON.stringify({ action: 'priority', priority: 10000, version: savedDraft.version }) });
  expect(priority.status).toBe(200);
  const doc = await claim(); expect(doc.id).toBe(draftId); expect(doc.details.generation.meter).toBe('3/4'); expect(doc.details.voiceModel).toBe(voice); expect(doc.details.generationProfile).toBe('v8');
  const lyrics = '[Verse]\nThe station clock was silent when the morning train pulled through\nI carried all your letters and the promise that I knew\n[Chorus]\nCarry me home across the rain\nCarry me home to you again\n[End]';
  const plan = { version: 1, title: 'Browser fixture — Across the rain', recipe: 'new', style: 'rock', keyscale: 'D minor', arrangement: 'Piano and cello waltz', lyrics, duration: 120, bpm: 98 };
  await call(`/prompts/${doc.id}/generation-review`, { leaseToken, reviewId: randomUUID(), kind: 'lyrics', payload: plan });
  await page.locator('#refresh-status').click(); await expect(page.locator('#review-lyrics')).toHaveValue(lyrics);
  const edited = lyrics.replace('silent', 'broken'); await page.locator('#review-lyrics').fill(edited);
  await page.reload(); await expect(page.locator('#review-lyrics')).toHaveValue(edited);
  await page.getByRole('button', { name: 'Approve lyrics & continue' }).click();
  await expect(page.locator('#review-lyrics')).toHaveCount(0);
  expect((await claim()).id).toBe(doc.id);
  const approved = (await call(`/prompts/${doc.id}/generation-review/lyrics`)).review;
  expect(approved.decision.lyrics).toBe(edited);
  await call(`/prompts/${doc.id}/plan`, { leaseToken, songPlan: { ...plan, lyrics: edited } });
  const audio = (await readFile('artifacts/v8/preview-fixture.mp3')).toString('base64');
  await call(`/prompts/${doc.id}/generation-review`, { leaseToken, reviewId: randomUUID(), kind: 'composition', payload: { candidates: [0,1].map((index) => ({ index, duration: 120, clips: ['Hook','Ending'].map((label) => ({ label, start: label === 'Hook' ? 30 : 90, duration: 15, audio })) })) } });
  await page.locator('#refresh-status').click(); await expect(page.locator('.composition-choice audio')).toHaveCount(4);
  for (const audio of await page.locator('.composition-choice audio').all()) {
    await expect.poll(() => audio.evaluate((a) => a.readyState)).toBeGreaterThan(0);
    await audio.evaluate(async (a) => { a.currentTime = 3; await a.play(); });
    await expect.poll(() => audio.evaluate((a) => a.currentTime)).toBeGreaterThan(3);
    await audio.evaluate((a) => a.pause());
  }
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/v8/choice-mobile.png', fullPage: true });
  await page.locator('input[name="composition"][value="1"]').check();
  await page.getByRole('button', { name: 'Use this composition', exact: true }).click();
  await expect(page.locator('.composition-choice')).toHaveCount(0); await page.reload();
  expect((await call(`/prompts/${doc.id}/generation-review/composition`)).review.decision.candidate).toBe(1);
  expect(errors).toEqual([]);
  await call(`/prompts/${doc.id}/fail`, { leaseToken: (await claim(), leaseToken), error: 'Browser test fixture finished; no song was generated.' });
});
