import { test, expect } from '@playwright/test';

test('mascot listens, smokes, stops on pause and follows songs across pages', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-04T19:00:00Z') });
  await page.route('**/yehry3/**', r => r.fulfill({ json: { songs: [], collections: [], items: [], listeners: [] } }));
  const wav = Buffer.alloc(44 + 8000 * 2 * 60);
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8);
  wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22);
  wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34);
  wav.write('data', 36); wav.writeUInt32LE(wav.length - 44, 40);
  await page.route('**/mascot-test.wav', r => r.fulfill({ contentType: 'audio/wav', body: wav }));
  await page.goto('/');
  const head = page.locator('.pumpkin-doomer-head');
  const animation = () => head.evaluate(n => getComputedStyle(n).animationName);
  await expect(page.locator('.pumpkin-doomer')).toBeVisible();
  expect(await animation()).toBe('none');
  await page.evaluate(() => window.yehry3Player.play({ id: 'mascot-test', title: 'Fixture song', url: '/mascot-test.wav' }));
  await expect(page.locator('html')).toHaveAttribute('data-doomer-listening', 'music');
  expect(await animation()).toBe('pumpkin-listening');
  const first = await head.evaluate(n => getComputedStyle(n).transform);
  await page.waitForTimeout(180);
  expect(await head.evaluate(n => getComputedStyle(n).transform)).not.toBe(first);
  await page.evaluate(() => window.yehry3Player.pause());
  await expect(page.locator('html')).toHaveAttribute('data-doomer-listening', 'idle');
  expect(await animation()).toBe('none');
  await page.evaluate(() => window.yehry3Player.play({ id: 'distonyc-d59c2b17c667891420654e76', title: 'Morning Routine', url: '/mascot-test.wav' }));
  await expect(page.locator('html')).toHaveAttribute('data-doomer-listening', 'morning');
  expect(await animation()).toBe('pumpkin-morning');
  expect(await head.evaluate(n => getComputedStyle(n).animationDuration)).toBe('0.648148s');
  await expect(page.locator('.pumpkin-doomer-smoke')).toHaveCSS('opacity', '1');
  expect(await page.locator('.pumpkin-doomer-smoke path').first().evaluate(n => getComputedStyle(n).animationName)).toBe('pumpkin-smoke');
  await page.screenshot({ path: 'test-results/pumpkin-listening-desktop.png' });
  await page.getByRole('link', { name: 'The queue', exact: true }).click();
  await expect(head).toBeVisible();
  await expect.poll(animation).toBe('pumpkin-morning');
  expect(await page.locator('#audio').evaluate(n => !n.paused && n.currentTime > 0)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/pumpkin-listening-phone.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => { window.yehry3Player.audio.muted = true; });
  await expect(page.locator('html')).toHaveAttribute('data-doomer-listening', 'idle');
  await page.evaluate(() => { window.yehry3Player.audio.muted = false; });
  await expect(page.locator('html')).toHaveAttribute('data-doomer-listening', 'morning');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  expect(await animation()).toBe('none');
  await expect(page.locator('.pumpkin-doomer-smoke')).toHaveCSS('opacity', '0');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.evaluate(async () => (await import('/assets/halloween-preferences.js')).setHalloweenLevel('low'));
  expect(await animation()).toBe('none');
  await page.evaluate(async () => (await import('/assets/halloween-preferences.js')).setHalloweenLevel('off'));
  await expect(page.locator('.pumpkin-doomer')).toBeHidden();
  await page.evaluate(() => window.yehry3Player.clear());
});
