import { createHash } from "node:crypto";
import { test, expect } from "@playwright/test";
const sheet = "[Verse 1]\nThe lantern catches all our names\nAnd brings the sleeping railway home\nWe keep the light until the morning comes";
async function start(page) {
  await page.goto("/distonyc/");
  await page.getByLabel("Password", { exact: true }).fill("wishbone");
  await page.getByRole("button", { name: "Let’s make something" }).click();
  await page.getByLabel("Your prompt").fill("A warm railway song with a lantern in the window");
  await page.getByRole("button", { name: "Find the direction" }).click();
  await page.getByRole("tab", { name: "Advanced", exact: true }).click();
  await page.locator(".request-materials > summary").click();
}
test("an older API keeps ordinary requests usable without silently accepting attachments", async ({ page }) => {
  await page.route("**/yehry3/request-materials", route => route.fulfill({ status: 404, json: { error: "Endpoint not found." } }));
  await page.goto("/distonyc/");
  await page.getByLabel("Password", { exact: true }).fill("wishbone");
  await page.getByRole("button", { name: "Let’s make something" }).click();
  await page.getByLabel("Your prompt").fill("An ordinary song during the coordinated rollout");
  await page.getByRole("button", { name: "Find the direction" }).click();
  await page.getByRole("tab", { name: "Advanced", exact: true }).click();
  await expect(page.getByText("Lyrics and reference links are temporarily unavailable.")).toBeVisible();
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.getByRole("button", { name: "Send to the queue" })).toBeEnabled();
});
test("lyrics persist through reload, review and editing, with default preservation and public boundaries", async ({ page }) => {
  await start(page);
  await expect(page.getByLabel("How should we use these lyrics?")).toHaveValue("preserve");
  await page.getByLabel("Lyric sheet", { exact: true }).fill(sheet);
  await page.reload();
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveValue(sheet);
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.locator(".materials-review")).toContainText("Keep my wording");
  await page.getByText("Read the submitted lyric sheet").click();
  await expect(page.locator(".material-text")).toHaveText(sheet);
  await page.reload();
  await expect(page.locator(".materials-review")).toContainText("Keep my wording");
  await page.getByRole("button", { name: "Fine-tune it" }).click();
  await page.getByLabel("How should we use these lyrics?").selectOption("adapt");
  await page.reload();
  await expect(page.getByLabel("How should we use these lyrics?")).toHaveValue("adapt");
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.locator(".materials-review")).toContainText("Adapt these lyrics");
  await expect(page.locator(".materials-review")).toContainText("public once the request is confirmed");
});
test("oversized sheets remain intact and long preserve requests offer adaptation before queueing", async ({ page }) => {
  await start(page);
  const field = page.getByLabel("Lyric sheet", { exact: true });
  const oversized = "word ".repeat(3001);
  await field.fill(oversized);
  await expect(page.locator("#lyric-count")).toContainText("3,001 / 3,000");
  await page.getByRole("tab", { name: "Essentials", exact: true }).click();
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.getByRole("tab", { name: "Advanced", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(field).toBeFocused();
  await expect(field).toHaveValue(oversized);
  await field.fill("word ".repeat(600));
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.getByRole("button", { name: "Send to the queue" })).toBeDisabled();
  await expect(page.locator("#confirm-form .field-error")).toContainText("5-minute");
  await page.getByRole("button", { name: "Fine-tune it" }).click();
  await page.getByLabel("How should we use these lyrics?").selectOption("adapt");
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.getByRole("button", { name: "Send to the queue" })).toBeEnabled();
});
test("each link has its own purpose and imported lyrics require an explicit replacement", async ({ page }) => {
  await start(page);
  await page.getByLabel("Lyric sheet", { exact: true }).fill(sheet);
  await page.route("**/yehry3/references/resolve", async route => {
    if (route.request().method() === "OPTIONS") return route.continue();
    const { url, purpose } = route.request().postDataJSON();
    await route.fulfill({ json: { reference: { url, purpose, snapshotId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", snapshot: {
      title: "<img src=x onerror=alert(1)>", status: "ready", kind: "text", text: sheet + "\nA different final line", message: "Lyrics retrieved. Check before using.",
    } } } });
  });
  await page.getByRole("button", { name: "Add a reference link" }).click();
  await page.getByLabel("Reference URL 1", { exact: true }).fill("https://example.org/lyrics.txt");
  await page.getByLabel("Use link 1 for").selectOption("lyrics");
  await page.getByRole("button", { name: "Preview link" }).click();
  await expect(page.getByLabel("Review imported lyrics 1")).toHaveValue(sheet + "\nA different final line");
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveValue(sheet);
  await page.getByLabel("Review imported lyrics 1").fill(sheet + "\nMy edited final line");
  await page.getByRole("button", { name: "Use these lyrics" }).click();
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveValue(sheet + "\nMy edited final line");
  await expect(page.locator(".reference-preview img")).toHaveCount(0);
  await page.getByRole("button", { name: "Add a reference link" }).click();
  await expect(page.getByLabel("Use link 2 for")).toHaveValue("creative");
  await page.getByRole("button", { name: "Add a reference link" }).click();
  await expect(page.getByRole("button", { name: "Add a reference link" })).toBeDisabled();
  await page.getByRole("button", { name: "Remove reference 3" }).click();
  await expect(page.getByRole("button", { name: "Add a reference link" })).toBeEnabled();
  await page.getByLabel("Reference URL 1", { exact: true }).fill("https://example.org/changed.txt");
  await expect(page.getByLabel("Review imported lyrics 1")).toHaveCount(0);
});
test("failed imports preserve pasted lyrics and the mobile form stays within the viewport", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await start(page);
  await page.getByLabel("Lyric sheet", { exact: true }).fill(sheet);
  await page.getByRole("button", { name: "Add a reference link" }).click();
  await page.getByLabel("Reference URL 1", { exact: true }).fill("https://youtu.be/abcdefghijk");
  await page.getByLabel("Use link 1 for").selectOption("lyrics");
  await page.getByRole("button", { name: "Preview link" }).click();
  await expect(page.locator(".reference-preview")).toContainText("Paste the lyric sheet");
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveValue(sheet);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "artifacts/request-materials-mobile.png", fullPage: true });
});

test("Advanced keeps direction, lyrics and basis songs through keyboard tab switches and review", async ({ page }) => {
  await start(page);
  const advanced = page.getByRole("tab", { name: "Advanced", exact: true });
  const essentials = page.getByRole("tab", { name: "Essentials", exact: true });
  const direction = page.getByLabel("What does it sound like?");
  await direction.fill("Warm guitar with a soft brushed rhythm.");
  await page.getByLabel("Lyric sheet", { exact: true }).fill(sheet);
  await page.locator(".basis-picker summary").click();
  await page.getByRole("checkbox", { name: /^Medusa \(/ }).check();
  await advanced.focus();
  await page.keyboard.press("ArrowLeft");
  await expect(essentials).toBeFocused();
  await expect(page.getByLabel("Tony voice model")).toHaveValue("v7");
  await expect(direction).toBeHidden();
  await page.getByLabel("What matters most?").fill("Keep the lantern hook.");
  await essentials.focus();
  await page.keyboard.press("End");
  await expect(advanced).toBeFocused();
  await expect(direction).toHaveValue("Warm guitar with a soft brushed rhythm.");
  await expect(page.getByLabel("Lyric sheet", { exact: true })).toHaveValue(sheet);
  await expect(page.getByRole("checkbox", { name: /^Medusa \(/ })).toBeChecked();
  await page.keyboard.press("Home");
  await expect(essentials).toBeFocused();
  await page.keyboard.press("ArrowRight");
  await expect(advanced).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  const soundBox = await direction.boundingBox();
  const lyricsBox = await page.locator("#request-materials-root").boundingBox();
  const basisBox = await page.locator("#basis-root").boundingBox();
  expect(soundBox.y + soundBox.height).toBeLessThan(lyricsBox.y);
  expect(lyricsBox.y + lyricsBox.height).toBeLessThan(basisBox.y);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await essentials.click();
  await page.screenshot({ path: "artifacts/request-essentials-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Review the request" }).click();
  await expect(page.locator(".brief")).toContainText("Warm guitar with a soft brushed rhythm.");
  await expect(page.locator(".brief")).toContainText("Keep the lantern hook.");
  await expect(page.locator(".brief")).toContainText("Medusa");
  await expect(page.locator(".materials-review")).toContainText("Keep my wording");
});

test("confirmed lyrics and references are readable in Backstage and without a login", async ({ page, browser }) => {
  await start(page);
  await page.getByLabel("What does it sound like?").fill("Acoustic guitar with brushed drums.");
  await page.getByLabel("Lyric sheet", { exact: true }).fill(sheet);
  await page.getByRole("button", { name: "Add a reference link" }).click();
  await page.getByLabel("Reference URL 1", { exact: true }).fill("https://example.org/lantern");
  await page.getByLabel("What should we take from reference 1?").fill("The warm evening atmosphere.");
  await page.getByRole("button", { name: "Review the request" }).click();
  await page.getByRole("button", { name: "Send to the queue" }).click();
  await expect(page.getByText("Your idea is on the list.")).toBeVisible();
  const id = await page.evaluate(() => sessionStorage.getItem("yehry3:draft"));
  await page.goto("/admin/?status=all");
  await page.getByLabel("Password", { exact: true }).fill(process.env.YEHRY3_TEST_ADMIN_PASSWORD || "browser-test-admin");
  await page.getByRole("button", { name: "Open the queue" }).click();
  const card = page.locator(`[data-prompt="${id}"]`);
  await expect(card.locator(".prompt-summary")).toContainText("Keep my wording");
  await expect(card.locator(".prompt-summary")).toContainText("1 reference link");
  await card.getByText("Open brief & controls").click();
  await card.getByText("Read the submitted lyric sheet").click();
  await expect(card.getByRole("region", { name: "Submitted lyric sheet" })).toHaveText(sheet);
  await expect(card.locator(".reference-note")).toContainText("The warm evening atmosphere.");
  await expect(card.locator(".brief")).toContainText("Acoustic guitar with brushed drums.");
  const publicContext = await browser.newContext();
  try {
    const visitor = await publicContext.newPage();
    await visitor.goto("http://127.0.0.1:8080/queue/");
    const publicSongId = "distonyc-" + createHash("sha256").update(id).digest("hex").slice(0, 24);
    const publicCard = visitor.locator(".public-queue-card").filter({ has: visitor.locator(`a[href="/original-prompt/?song=${publicSongId}"]`) });
    await publicCard.getByRole("link", { name: "View original prompt" }).click();
    await visitor.getByText("Read the submitted lyric sheet").click();
    await expect(visitor.getByRole("region", { name: "Submitted lyric sheet" })).toHaveText(sheet);
    await expect(visitor.locator(".reference-note")).toContainText("The warm evening atmosphere.");
    await expect(visitor.locator(".reference-review a")).toHaveAttribute("href", "https://example.org/lantern");
    await expect(visitor.getByLabel("Password", { exact: true })).toHaveCount(0);
  } finally {
    await publicContext.close();
  }
  await card.getByLabel("Move request to").selectOption("canceled");
  page.once("dialog", dialog => dialog.accept());
  await card.getByRole("button", { name: "Update status" }).click();
  await expect(card.locator(".badge")).toHaveText("Canceled");
});
