"""Export only public song IDs and settled generation cents from the private ledger.

Run with --ledger <path>. No provider call, ledger write, or credentials are needed.
Unsettled songs are omitted so the cards can show their labeled estimates.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'pc-worker'))
from paid_music import validate_ledger
from push_music_settlement import settlement_rows


def public_costs(catalog, ledger):
    validate_ledger(ledger)
    completed = {row['id'] for row in ledger['requests'] if row.get('status') == 'completed'}
    published = {song['id'] for song in catalog['songs'] if song.get('musicBackend') == 'eleven_music'}
    costs = {}
    for row in settlement_rows(ledger):
        # Chairlift worker-store.js derives the public song ID from the full request ID.
        song_id = 'distonyc-' + hashlib.sha256(row['id'].encode()).hexdigest()[:24]
        if row['id'] in completed and not row['pending'] and song_id in published:
            costs[song_id] = row['settled']
    return dict(sorted(costs.items()))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ledger', required=True, type=Path)
    args = parser.parse_args()
    costs = public_costs(json.loads((ROOT / 'catalog.json').read_text(encoding='utf-8')),
                         json.loads(args.ledger.read_text(encoding='utf-8')))
    output = ROOT / 'assets' / 'settled-song-costs.js'
    output.write_text('// Generated by scripts/sync-song-costs.py; public song IDs and settled USD cents only.\n'
                      + 'export const settledSongCosts = Object.freeze('
                      + json.dumps(costs, indent=2) + ');\n', encoding='utf-8')
    print(f'Exported {len(costs)} settled song costs to {output.name}.')


if __name__ == '__main__':
    main()
